apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sa74ib4ce-go 
  janus-idp.io/tekton: sa74ib4ce-go
  backstage.io/kubernetes-id: sa74ib4ce-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sa74ib4ce-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  