apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sa74ib4ce-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:33baca6538f99259adf2ec6aec2663fb8dabeb50@sha256:03fb67591c9cd1b3a2b904a86b2373616c8c50cc7743ef038b223a7e2b4e2c3e
          name: container-image
